name: unit testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: sudo apt-get install libgtest-dev libeigen3-dev && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ../
            
    - name: Build
      run: cmake --build build --target all -j8
      
    - name: run tests
      run: |
        cd build
        ctest -VV -R testall